package com.bsopa.service;

import com.bsopa.dao.BookInfoDao;
import com.bsopa.pojo.BookInfo;

public class BookService {

	private BookInfoDao bookInfoDao;

	public BookInfoDao getBookInfoDao() {
		return bookInfoDao;
	}

	public void setBookInfoDao(BookInfoDao bookInfoDao) {
		this.bookInfoDao = bookInfoDao;
	}

	public void saveBook(BookInfo bookInfo) {
		bookInfoDao.saveBook(bookInfo);
		System.out
				.println("Book Information Save Successfully With Autogenerated ID");
	}
}
